//
//  AppConstants.swift
//  iPadOSKit
//
//  Created by HYEONMIN YOO on 18/01/2025.
//

enum Titles: String, CaseIterable {
    case first = "NumberPad"
    case second = "SignablePDF"
    case third = "Third"
    case fourth = "Fourth"
    case sixth = "Sixth"
    case seventh = "Seventh"
    case eighth = "Eighth"
    case night = "Nineth"
    case ten = "Ten"
    case eleven = "Eleventh"
    case twelve = "Twelveth"
    case thirteen = "Thirteenth"
    case fourteenth = "Fourteenth"
    case fifteenth = "Fifthteenth"
    case sixteenth = "Sixteenth"
    case seventeenth = "Seventeenth"
    case eighteenth = "Eighteenth"
    case nineteenth = "Nineteenth"
    case twentyth = "Twentyth"
    case twentyFirst = "Twenty-first"
    case twentySecond = "Twenty-second"
    case twentyThird = "Twenty-thrid"
    case twentyFourth = "Twenty-fourth"
    case twentyFifth = "Twenty-fifth"
    case twentySixth = "Twenty-sixth"
    case twentySeventh = "Twenty-senventh"
    case twentyEighth = "Twenty-eighth"
    case twentyNineth = "Twenty-nineth"
    case thirty = "Thirty"
}

enum ViewColors: String, CaseIterable {
    case first = "#003366"
    case second = "#708090"
    case third = "#006400"
    case fourth = "#6B8E23"
    case sixth = "#800020"
    case seventh = "#2F4F4F"
    case eighth = "#8B0000"
    case night = "#000000"
    case ten = "#4B0082"
    case eleven = "#008B8B"
    case twelve = "#006666"
    case thirteen = "#FF4500"
    case fourteenth = "#8B4513"
    case fifteenth = "#800080"
    case sixteenth = "#556B2F"
    case seventeenth = "#36454F"
    case eighteenth = "#00008B"
    case nineteenth = "#FFD700"
    case twentyth = "#FF8C00"
    case twentyFirst = "#C71585"
    case twentySecond = "#191970"
    case twentyThird = "#0D98BA"
    case twentyFourth = "#F1C40F"
    case twentyFifth = "#B5651D"
    case twentySixth = "#A9BFA7"
    case twentySeventh = "#4169E1"
    case twentyEighth = "#FFDB58"
    case twentyNineth = "#B22222"
    case thirty = "#D4E1A0"
}
